"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.authRouter = void 0;
const express_1 = require("express");
const authController_1 = require("../controllers/authController");
const validators_1 = require("../utils/validators/validators");
exports.authRouter = (0, express_1.Router)({});
exports.authRouter.post("/", validators_1.nameIsInvalid, validators_1.nameIsReuared, validators_1.inputValidatorsMiddleware, authController_1.auth);
exports.authRouter.get("/me/:token", authController_1.me);
exports.authRouter.post("/logout/:token", authController_1.logout);
